### PR TITLE
Update Diff.php for VersionStrategy::DIFF

### PR DESCRIPTION
**Pull request by SirajCse**
new and old both view sideBySide ->reverse()

foreach ($versionsBeforeThis->reverse() as $version) {
                if (! empty($version->contents)) {
                    $oldContents = array_merge($oldContents, $version->contents);
                }
            }

### CODE REVIEW

**Review by slizhva — APPROVED** [review]

**Comment by overtrue** [comment]
@mansoorkhan96 Can you help me to review this? thanks!

**Comment by mansoorkhan96** [comment]
> @mansoorkhan96 Can you help me to review this? thanks!

Hey,
I just tested this and it works. I did not see any significant changes thought.
Not sure what is the reason / expected behaviour. Any thoughts @SirajCse

**Comment by SirajCse** [comment]
@mansoorkhan96 @mansoorkhan96  
 If you use Store strategy VersionStrategy::DIFF it 'Revisions List' is in reverse order otherwise it shows older list data first.

**Comment by overtrue** [comment]
@SirajCse Thanks!

**Pull request merged**
